export const CHECK_ALL = 'CHECK_ALL'
export const NO_CHECK_ALL = 'NO_CHECK_ALL'
export const CHECK_WITHOUT = 'CHECK_WITHOUT'
export const NO_CHECK_WITHOUT = 'NO_CHECK_WITHOUT'
export const CHECK_ONE = 'CHECK_ONE'
export const NO_CHECK_ONE = 'NO_CHECK_ONE'
export const CHECK_TWO = 'CHECK_TWO'
export const NO_CHECK_TWO = 'NO_CHECK_TWO'
export const CHECK_THREE = 'CHECK_THREE'
export const NO_CHECK_THREE = 'NO_CHECK_THREE'

export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const GET_TICKETS = 'GET_TICKETS'
export const SORT_CHEAP = 'SORT_CHEAP'
export const SORT_FAST = 'SORT_FAST'
export const ON_ERROR = 'ON_ERROR'
export const ON_ALERT = 'ON_ALERT'

export const ONLINE = 'ONLINE'
export const OFFLINE = 'OFFLINE'
